
POST http://localhost:8080/create-user HTTP/1.1
Content-Type: application/json

{
    "username":"Yae Wint Aung",
    "email":"me@gmail.com",
    "chatId":null,
    "interest":"asdf"
}
###
POST http://localhost:8080/create-group HTTP/1.1
Content-Type: application/json

{
    "user_id":"01K7KGV79HHKTCWTP9YWXFEX1Y",
    "group_title":"To do fir"
}
###
POST https://zelusonice.dpdns.org/update/api-key HTTP/1.1
Content-Type: application/json

{
    "key":"key3"
}

###
POST http://localhost:8080/create-task HTTP/1.1
Content-Type: application/json

{
    "user_id":"01K7KGV79HHKTCWTP9YWXFEX1Y",
    "group_id":"01K7KH4XA3DMAV9WAW6QQKQ306",
    "title":"Task2",
    "date":"2025-10-15T12:25:55.857Z"
}
###
GET http://52.220.246.106/user/01K7KGV79HHKTCWTP9YWXFEX1Y HTTP/1.1
###
GET http://localhost:8080/groups/01K7KGV79HHKTCWTP9YWXFEX1Y HTTP/1.1
###
GET http://localhost:8080/groups/01K7KGV79HHKTCWTP9YWXFEX1Y/01K7KH4XA3DMAV9WAW6QQKQ306 HTTP/1.1

###
POST https://ventureserver-3h0i.onrender.com/update/telegram-model HTTP/1.1
Content-Type: application/json

{
    "model_name":"deepseek/deepseek-chat-v3.1:free"
}